import type { BuildExecutorReceiptView, BuildExecutorView, RollbackStopCheck } from '../types';

export const BUILD_EXECUTOR_ALLOWED_REPO = 'D:\\Projects\\agent-hub-demo';
export const BUILD_EXECUTOR_ALLOWED_CWD = BUILD_EXECUTOR_ALLOWED_REPO;
export const BUILD_EXECUTOR_ALLOWED_COMMAND = 'npm run build';

export const BUILD_EXECUTOR_PROTECTED_PATHS = [
  'package.json',
  'package-lock.json',
  'pnpm-lock.yaml',
  'yarn.lock',
  'vite.config.ts',
  'vite.config.js',
  'tsconfig.json',
  'src/index.css',
  'src/App.css',
] as const;

function pass(id: string, label: string, evidence: string): RollbackStopCheck {
  return {
    id,
    label,
    status: 'pass',
    evidence,
  };
}

export const buildExecutorView: BuildExecutorView = {
  build_executor_v0_1: true,
  build_executor_implemented: true,
  build_executor_executed: true,
  allowed_command: BUILD_EXECUTOR_ALLOWED_COMMAND,
  allowed_cwd: BUILD_EXECUTOR_ALLOWED_CWD,
  shell: false,
  npm_install_update_allowed: false,
  dev_preview_test_allowed: false,
  package_config_css_dependency_change_allowed: false,
  stage_permission: false,
  commit_permission: false,
  push_permission: false,
  summary:
    'Build executor v0.1 is implemented as a single-command local Node wrapper. It only executes npm run build with shell=false and records a receipt.',
  allowedCommands: [BUILD_EXECUTOR_ALLOWED_COMMAND],
  forbiddenCommands: [
    'npm install',
    'npm update',
    'npm run dev',
    'npm run preview',
    'npm test',
    'arbitrary npm scripts',
    'shell concatenation',
    'Git stage/commit/push',
  ],
  receiptRequirements: [
    'approval_id',
    'executor_mode',
    'command',
    'cwd',
    'exit_code',
    'warnings summary',
    'pre/post git status',
    'package/package-lock/config/CSS diff check',
    'artifact policy',
    'receipt_status',
  ],
  artifactPolicy: [
    'dist output may be generated by Vite but is not staged by the executor',
    'package, lockfile, config, and CSS files must remain unchanged',
    'build receipt is evidence only and does not authorize stage/commit/push',
  ],
  stopConditions: [
    'requested command is not npm run build',
    'cwd is not the approved repo',
    'shell mode or command concatenation is requested',
    'npm install/update/dev/preview/test is requested',
    'package/config/CSS/dependency diff appears after build',
    'build exit code is nonzero',
  ],
};

export const buildExecutorReceiptView: BuildExecutorReceiptView = {
  receipt_id: 'DemoScenario055-FIRST-BUILD-EXECUTOR-20990101',
  approval_id: 'DemoScenario056-build-executor-first-run-approval-20990101',
  executor_mode: 'build_executor_v0_1',
  command: BUILD_EXECUTOR_ALLOWED_COMMAND,
  cwd: BUILD_EXECUTOR_ALLOWED_CWD,
  exit_code: 0,
  warnings_summary: 'existing Vite large chunk warning only',
  pre_status_summary: 'DemoScenario056 approved implementation and fixture paths dirty before manual commit',
  post_status_summary: 'same approved paths dirty; staged empty; HEAD unchanged by executor',
  package_package_lock_diff_check: 'unchanged',
  package_config_css_dependency_diff_check: 'unchanged',
  artifact_policy: 'dist generated output not staged; package/config/CSS/dependency unchanged',
  receipt_status: 'executed_build_executor_passed',
  verification_status: 'pass',
  stop_checks: [
    pass('allowed_command_exact', 'command equals npm run build', BUILD_EXECUTOR_ALLOWED_COMMAND),
    pass('allowed_cwd_exact', 'cwd matches approved repo', BUILD_EXECUTOR_ALLOWED_CWD),
    pass('shell_false', 'shell mode is false', 'spawn node.exe npm-cli.js run build with argv only'),
    pass('exit_code_zero', 'exit code is 0', 'npm run build passed'),
    pass('protected_paths_unchanged', 'package/config/CSS/dependency unchanged', 'diff check empty'),
    pass('stage_commit_push_false', 'stage/commit/push executor not used', 'manual git gate only'),
  ],
};
